name: Conventional Commit Checker
description: Checks commit messages against conventional commit format

inputs:
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: node20
  main: src/index.js
