name: Commit Harmonizer
description: Checks commit messages against Conventional Commit format
author: aisevim
branding:
  icon: align-center
  color: gray-dark

inputs:
  github-token:
    description: "GitHub token"
    required: true

  has-commits:
    description: "Check commits"
    default: true

  has-pr-title:
    description: "Check PR title"
    default: true

  color-level:
    description: "Color level, see https://github.com/chalk/chalk?tab=readme-ov-file#supportscolor"
    default: 0

runs:
  using: node20
  main: dist/index.js
