name: Conventional Commit Checker
description: Checks commit messages against conventional commit format
author: aisevim

inputs:
  github-token:
    description: 'GitHub token'
    required: true

  has-commits:
    description: 'Check commits'
    default: true

  has-pr-title:
    description: 'Check PR title'
    default: true

runs:
  using: node20
  main: src/index.js
