name: Commit Harmonizer
description: Checks commit messages against Conventional Commit format
author: aisevim
branding:
  icon: align-center
  color: gray-dark

inputs:
  github-token:
    description: "GitHub token"
    required: true

  check-commits:
    description: "Check commits"
    default: true

  check-pr-title:
    description: "Check PR title"
    default: true

runs:
  using: node20
  main: dist/index.js
